// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXVKnzXyCXO8Vnad3SgCn6t-aDGmfzgaw',
    appId: '1:996972065274:web:12aac7d07d6cf33f4f7443',
    messagingSenderId: '996972065274',
    projectId: 'doctor-of-plant',
    authDomain: 'doctor-of-plant.firebaseapp.com',
    databaseURL: 'https://doctor-of-plant-default-rtdb.firebaseio.com',
    storageBucket: 'doctor-of-plant.appspot.com',
    measurementId: 'G-B7BJJ1NWPT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCykA5_waoHHZFZcifksrfn9VJipfEIlNw',
    appId: '1:996972065274:android:a5cedbc6a6a3bcbd4f7443',
    messagingSenderId: '996972065274',
    projectId: 'doctor-of-plant',
    databaseURL: 'https://doctor-of-plant-default-rtdb.firebaseio.com',
    storageBucket: 'doctor-of-plant.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAE7_TnIzZNBOrWK1JR38VW8tgBAy16-4',
    appId: '1:996972065274:ios:e9896d8e7c72f2314f7443',
    messagingSenderId: '996972065274',
    projectId: 'doctor-of-plant',
    databaseURL: 'https://doctor-of-plant-default-rtdb.firebaseio.com',
    storageBucket: 'doctor-of-plant.appspot.com',
    iosBundleId: 'com.example.doctorOfPlantAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAE7_TnIzZNBOrWK1JR38VW8tgBAy16-4',
    appId: '1:996972065274:ios:fa03aa885cca1a044f7443',
    messagingSenderId: '996972065274',
    projectId: 'doctor-of-plant',
    databaseURL: 'https://doctor-of-plant-default-rtdb.firebaseio.com',
    storageBucket: 'doctor-of-plant.appspot.com',
    iosBundleId: 'com.example.doctorOfPlantAdmin.RunnerTests',
  );
}
