// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOHBZrs_oNETerdtcD9MVGelEoz_yVcUk',
    appId: '1:857952296680:web:313c401b43e717041af35d',
    messagingSenderId: '857952296680',
    projectId: 'ecommerce-d1f29',
    authDomain: 'ecommerce-d1f29.firebaseapp.com',
    storageBucket: 'ecommerce-d1f29.appspot.com',
    measurementId: 'G-RVQMBELRJW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq7P1QahqSvvRZJPYTyOBo0FrsgUS6yCo',
    appId: '1:857952296680:android:f7070de7a383f3ee1af35d',
    messagingSenderId: '857952296680',
    projectId: 'ecommerce-d1f29',
    storageBucket: 'ecommerce-d1f29.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACMCJIIff8887RL8vTcbP2G7kk6hiCarU',
    appId: '1:857952296680:ios:f7103e30f33045b81af35d',
    messagingSenderId: '857952296680',
    projectId: 'ecommerce-d1f29',
    storageBucket: 'ecommerce-d1f29.appspot.com',
    androidClientId: '857952296680-dnrd97t132ll9p62brg3f2ea10pae1mr.apps.googleusercontent.com',
    iosClientId: '857952296680-71t8oleua9gmbm2s1bf1tphdr5nkvteh.apps.googleusercontent.com',
    iosBundleId: 'com.example.doctorPlanAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACMCJIIff8887RL8vTcbP2G7kk6hiCarU',
    appId: '1:857952296680:ios:553a4e3a22c7de771af35d',
    messagingSenderId: '857952296680',
    projectId: 'ecommerce-d1f29',
    storageBucket: 'ecommerce-d1f29.appspot.com',
    androidClientId: '857952296680-dnrd97t132ll9p62brg3f2ea10pae1mr.apps.googleusercontent.com',
    iosClientId: '857952296680-0r1hqhlorddn9vbm8ltrv9mhqonlie8s.apps.googleusercontent.com',
    iosBundleId: 'com.example.doctorPlanAdmin.RunnerTests',
  );
}
